In [1]:
import numpy as np

# Using Built-in Functions to Create ndarrays

In [ ]:
x = np.array([1,2,5])
x

In [10]:
X = np.zeros((3,4), dtype = int)
X

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
x = np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
x = np.full((3,4), 5)
x

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [16]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
x = np.diag([1,5,7,10])
x

array([[ 1,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0,  7,  0],
       [ 0,  0,  0, 10]])

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x = np.arange(0,20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
a = np.arange(1,40,10)
a

array([ 1, 11, 21, 31])

In [28]:
x = np.reshape(x, (4,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
x = np.random.random((3,4))
x

array([[0.7514465 , 0.83464663, 0.06930121, 0.40572799],
       [0.88861719, 0.4041287 , 0.69868964, 0.3989365 ],
       [0.78429397, 0.79117859, 0.52893132, 0.96935648]])

In [33]:
x = np.random.randint(3,14, (3,4))
x

array([[ 7,  3,  3, 13],
       [12,  4,  6, 13],
       [ 3,  3,  7, 10]])

In [35]:
x = np.random.normal(0, 0.1, size=(5,5)) # 0 = mean; 0.1 = standard deviation; size=(5,5) matrix of 5*5
x

array([[-0.21136485,  0.01183094,  0.09653708,  0.00259918,  0.08286284],
       [ 0.16942847, -0.12284393,  0.05101251, -0.07561963, -0.23423454],
       [ 0.00839457, -0.03977976,  0.09887909, -0.03615046, -0.00347404],
       [ 0.00142825, -0.05677435,  0.01728441, -0.05494154, -0.16749036],
       [-0.1222502 , -0.14583672, -0.02000528,  0.05993343,  0.10024376]])

In [46]:
x = np.arange(2,34,2).reshape((4,4))
x

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

# Accessing, Deleting, and Inserting Elements Into ndarrays

In [55]:
x = np.array([4,5,7,8,4])
print("1st element =",x[0])

1st element = 4


In [49]:
x[3] = 15

In [50]:
x

array([ 4,  5,  7, 15,  4])

In [59]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
print("element at (0,0) =",x[0,0])
print("element at (1,2) =",x[0,1])
print("element at (2,2) =",x[1,1])

element at (0,0) = 1
element at (1,2) = 2
element at (2,2) = 5


In [68]:
w = np.delete(x, 0, axis = 0)
w

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
w = np.delete(x, [0,2], axis = 1)
w

array([[2],
       [5],
       [8]])

In [72]:
w = np.append(x, 69)
w

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 69])

In [74]:
w = np.append(x, [10,47])
w

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 47])

In [80]:
x = np.arange(1,10).reshape(3,3)
w = np.append(x , [[48,45,78]], axis = 0) #append to row
w

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [48, 45, 78]])

In [82]:
w = np.append(x , [[48],[45],[78]], axis = 1) #append to coloumn
w

array([[ 1,  2,  3, 48],
       [ 4,  5,  6, 45],
       [ 7,  8,  9, 78]])

In [96]:
x = np.array([1,14,19])
w = np.insert(x, 2, [48, 75])
w

array([ 1, 14, 48, 75, 19])

In [93]:
x = np.arange(1,10).reshape(3,3)
w = np.insert(x, 1, [23,34,96], axis = 0)
w

array([[ 1,  2,  3],
       [23, 34, 96],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [104]:
x = np.arange(1,10).reshape(3,3)
y = np.insert(x, 1, 69, axis = 1)
y

array([[ 1, 69,  2,  3],
       [ 4, 69,  5,  6],
       [ 7, 69,  8,  9]])

# Slicing ndarrays

In [107]:
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [117]:
z = x[1:4, 2:5]#[row, coloumn]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [120]:
z = x[1:, 2:]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [123]:
z = x[:2, :2]
z

array([[1, 2],
       [6, 7]])

In [128]:
z = x[:, 4]#Coloumn 5
z 

array([ 5, 10, 15, 20])

In [129]:
z = x[2, :]#Row 3
z

array([11, 12, 13, 14, 15])

In [137]:
# changing element in Z will also change the element in x
z = x[1:, 2:]
z[1,1] = 55
print(z)
print("\n",x)

[[ 8  9 10]
 [13 55 15]
 [18 96 20]]

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 69 13 55 15]
 [16 17 18 96 20]]


In [143]:
x =np.arange(1,21).reshape(4,5)
z
z = x[1:, 2:].copy()
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [144]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Boolean Indexing, Set Operations, and Sorting

In [148]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [149]:
x[x > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [150]:
x[x<=21]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [156]:
x[(x>10) & (x < 23)] = 44
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 23, 24]])

In [158]:
x = np.array([4,1,2,5,10,4])
y = np.array([4,11,21,7,10])
print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))


[ 4 10]
[1 2 5]
[ 1  2  4  5  7 10 11 21]


In [160]:
np.sort(np.unique(x))

array([ 1,  2,  4,  5, 10])

In [163]:
x = np.random.randint(1,11, size=(5,5))
x

array([[ 5,  1,  8,  8,  1],
       [ 1,  3,  8,  5,  3],
       [ 8,  8,  4,  4,  6],
       [ 5, 10,  7,  8, 10],
       [ 1,  9,  1,  6,  2]])

In [165]:
np.sort(x, axis = 0)

array([[ 1,  1,  1,  4,  1],
       [ 1,  3,  4,  5,  2],
       [ 5,  8,  7,  6,  3],
       [ 5,  9,  8,  8,  6],
       [ 8, 10,  8,  8, 10]])

In [166]:
np.sort(x, axis = 1)

array([[ 1,  1,  5,  8,  8],
       [ 1,  3,  3,  5,  8],
       [ 4,  4,  6,  8,  8],
       [ 5,  7,  8, 10, 10],
       [ 1,  1,  2,  6,  9]])